#   ___  __    ____    __    _  _    ___   ___
#  / __)(  )  ( ___)  /__\  ( \( )  / __) / __)
# ( (__  )(__  )__)  /(__)\  )  (   \__ \( (__
#  \___)(____)(____)(__)(__)(_)\_)  (___/ \___)
#
# Configuration file.

settings:

  # By activating this option, the console will be able to send messages (not receive them) in staffchat.
  console_staffchat: true
  console_name: "Console"

  # Activating these options, staff members will receive a message when another staff member enters/leaves the server.
  staff_join_message: true
  staff_quit_message: true
  staff_join_all_players: false # By activating it, the staff will receive a message every time any player enters the server.
  staff_quit_all_players: false # By activating it, the staff will receive a message every time any player leaves the server.

  # You can customise permissions.
  staffchat_use_permission: "staffchat.use"
  staffchat_mute_permission: "staffchat.mute"
  staffchat_toggle_permission: "staffchat.toggle"
  staffchat_reload_permission: "staffchat.reload"


messages:

  # General
  prefix: "&c&lSC &8»"
  arguments: "%prefix% &7Use &d/sc <message>&7."

  # StaffChat talk messages.
  staffchat_talk_enabled: "%prefix% &7Now your messages will be sent in the &aStaffChat&7."
  staffchat_talk_disabled: "%prefix% &7Now your messages will be sent in the &achat&7."

  # StaffChat mute messages.
  staffchat_muted: "%prefix% &7StaffChat has been &amuted&7."
  staffchat_unmuted: "%prefix% &7StaffChat has been &aunmuted&7."

  # StaffChat toggle messages.
  staffchat_toggled_on: "%prefix% &7The StaffChat is now &avisible&7."
  staffchat_toggled_off: "%prefix% &7The StaffChat is now &ainvisible&7."

  # Chat Formats (If you use LuckPerms you can use %displayname%, %userprefix% and %usersuffix%).
  staffchat_format: "%prefix% &7%user% &8» &7%message%"
  staff_join_message_format: "%prefix% &7[&a+&7] &f&7%user%"
  staff_quit_message_format: "%prefix% &7[&c-&7] &f&7%user%"
  staff_switch_message_format: "%prefix% &7%user% &e➜ %server%" # This won't work if you run your plugin on spigot.

  # Errors and reload.
  no_permission: "%prefix% &cYou don't have the permission to do this."
  console: "%prefix% &cYou must be a player to use that command."
  staffchat_muted_error: "%prefix% &7StaffChat is actually &cmuted&7 by an operator!"
  reloaded: "%prefix% &7The StaffChat has been &areloaded&7!"
  module_disabled: "%prefix% &7This function is actually &cdisabled&7!"


modules:

  update_check: true
  stats: true

  staffchat_switch_module: true
  staffchat_talk_module: true
  staffchat_mute_module: true
  staffchat_toggle_module: true


# Enjoy.