#   ___  __    ____    __    _  _   ___  ___
#  / __)(  )  ( ___)  /__\  ( \( ) / __)/ __)
# ( (__  )(__  )__)  /(__)\  )  (  \__ \\__ \
#  \___)(____)(____)(__)(__)(_)\_) (___/(___/
# Configuration file. Made with ❤ by frafol.
# For support: discord.io/futuredevelopment


settings:

  # Name of the Hack Control server and the fallback server.
  server_name: "Control"
  fallback_server_name: "Hub"

  # This will check if you have been properly connected to the control server,
  # and if not, it will exit the control. If you encounter an error in the console
  # telling you that the server may be offline or crashed,
  # but you are sure that this is active, disable this feature.
  check_for_problems: true

  update_check: true
  stats: true

  slog:
    # WARNING! This will only work if you have LiteBans on your Proxy. At this time, no other bans plugins are supported.
    punish: false

    # Enter the command to be executed by the console when the player disconnects from the server.
    punish_command: "ban %player% Slog under hack control -s"

permissions:

  # You can personalize permissions.
  control: screenshare.control
  info: screenshare.info
  bypass: screenshare.bypass
  reload: screenshare.reload

discord-webhook: # The Discord Integration is an experimental feature, report all problems on our Discord.

  # Toggle discord feature.
  enabled: false

  # Your Discord bot's token.
  token: ""

  # Types: WATCHING, PLAYING, STREAMING.
  activity_type: "WATCHING"

  # The Discord bot's activity. You can use %players% to see the amount of players online.
  activity: "%players% online players."

  # To use CleanScreenShare with Discord, enter the ID of the chat where you want messages to be sent.
  channel_id: ""

  # The 'title' of the embed message sent on Discord.
  embed_title: "ScreenShare handler"

mysql:
  # The MySQL database is an experimental feature, it's just to allow compatibility with multiple proxies (e.g. redisbungee)
  enable: false

  # MySQL database connection details
  host: "127.0.0.1:3306"
  user: "root"
  database: "cleanscreenshare"
  password: "password"
  arguments: "?autoReconnect=true&maxReconnects=10"

# Enjoy.
