#   ___  __    ____    __    _  _    ___   ___
#  / __)(  )  ( ___)  /__\  ( \( )  / __) / __)
# ( (__  )(__  )__)  /(__)\  )  (   \__ \( (__
#  \___)(____)(____)(__)(__)(_)\_)  (___/ \___)
#
# Configuration file. Made with ❤ by frafol.
# For support: discord.io/futuredevelopment

settings:

  # By activating this option, the console will be able to send messages (not receive them) in staffchat.
  console_staffchat: true
  console_name: "Console"

  reload_permission: "staffchat.reload"

  use_staffchat: true
  use_adminchat: true
  use_donorchat: true

  staffchat:

    # Activating these options, staff members will receive a message when another staff member enters/leaves the server.
    staff_join_message: true
    staff_quit_message: true
    staff_join_all_players: false # By activating it, the staff will receive a message every time any player enters the server.
    staff_quit_all_players: false # By activating it, the staff will receive a message every time any player leaves the server.
    staff_switch_all_players: false # By activating it, the staff will receive a message every time any player switch a server.
    staff_disable_afk_on_move: true # On Velocity and BungeeCord, this works when a player changes server.

    # You can customise permissions.
    staffchat_use_permission: "staffchat.use"
    staffchat_mute_permission: "staffchat.mute"
    staffchat_toggle_permission: "staffchat.toggle"
    staffchat_afk_permission: "staffchat.afk"

  adminchat:

    # You can customise permissions.
    adminchat_use_permission: "adminchat.use"
    adminchat_mute_permission: "adminchat.mute"
    adminchat_toggle_permission: "adminchat.toggle"
    adminchat_afk_permission: "adminchat.afk"

  donorchat:

    # Cooldown in seconds, to disable set it to 0.
    cooldown: 30
    donorchat_discord_cooldown_bypass: false

    # You can customise permissions.
    donorchat_use_permission: "donorchat.use"
    donorchat_mute_permission: "donorchat.mute"
    donorchat_toggle_permission: "donorchat.toggle"
    donorchat_afk_permission: "donorchat.afk"
    donorchat_cooldown_bypass_permission: "donorchat.bypass"

  # By activating this option, you will not be able to send messages with formatting codes (&c, &f etc.).
  prevent_color_codes: false

modules:

  update_check: true
  stats: true

  staffchat_switch_module: true
  staffchat_afk_module: true
  staffchat_talk_module: true
  staffchat_mute_module: true
  staffchat_toggle_module: true
  staffchat_discord_module: true
  staffchat_discord_join_leave_module: true

  adminchat_switch_module: true
  adminchat_afk_module: true
  adminchat_talk_module: true
  adminchat_mute_module: true
  adminchat_toggle_module: true
  adminchat_discord_module: true

  donorchat_switch_module: true
  donorchat_afk_module: true
  donorchat_talk_module: true
  donorchat_mute_module: true
  donorchat_toggle_module: true
  donorchat_discord_module: true


# Enjoy.