name: CleanStaffChat
version: '${project.version}'
main: it.frafol.cleanstaffchat.spigot.CleanStaffChat
authors: [ frafol ]
description: Best StaffChat plugin.
softdepend:
  - LuckPerms
commands:
  sc:
    description: Use staffchat
    aliases: [staffchat, cleansc, cleanstaffchat]
  scmute:
    description: Mute staffchat
    aliases: [staffchatmute, cleanscmute, cleanstaffchatmute, staffmute]
  sctoggle:
    description: Toggle staffchat
    aliases: [staffchattoggle, cleansctoggle, cleanstaffchattoggle, staffchatoggle, cleanstaffchatoggle, stafftoggle]
  screload:
    description: Reload staffchat
    aliases: [staffchatreload, cleanscreload, cleanstaffchatreload, staffreload]
  scafk:
    description: Reload staffchat
    aliases: [staffchatafk, cleanscafk, cleanstaffchatafk, staffafk]