name: CleanStaffChat
version: '${project.version}'
main: it.frafol.cleanstaffchat.bukkit.CleanStaffChat
authors: [ frafol ]
description: Best StaffChat plugin.
api-version: 1.13
folia-supported: true
softdepend:
  - LuckPerms
  - UltraPermissions
  - PremiumVanish
  - SuperVanish