name: CleanStaffChat
version: '${project.version}'
main: it.frafol.cleanstaffchat.bukkit.CleanStaffChat
authors: [ frafol ]
description: Best StaffChat plugin.
folia-supported: true
softdepend:
  - LuckPerms
  - UltraPermissions