#   ___  __    ____    __    _  _   ___  ___
#  / __)(  )  ( ___)  /__\  ( \( ) / __)/ __)
# ( (__  )(__  )__)  /(__)\  )  (  \__ \\__ \
#  \___)(____)(____)(__)(__)(_)\_) (___/(___/
# Settings file. Made with ❤ by frafol.
# For support: discord.io/futuredevelopment

options:

  update_check: true
  auto_update: true

  # Bypass command and move prevention.
  staff_permission: "screenshare.control"
  admin_permission: "screenshare.admin"

  # Makes all online players invincible.
  invincible: true

  # Teleports to Spawn at Join.
  teleport_to_spawn_on_join: true

  # Change player's gamemode on player's join.
  # Supported values: survival, creative, adventure, spectator.
  # If you want to disable this feature, set this value to "none".
  change_gamemode_on_join: "adventure"

  # Action preventions.
  prevent:

    # Prevent player actions.
    player:
      block_place: true
      block_break: true
      move: false
      pvp: true
      void: true
      hunger: true
      chat: true

    # Prevent world changes.
    world:
      weather_change: true
      daylight_cycle: true
      mob_spawning: true

  messages:
    spawn_set: "&aSpawn has been set in your position."

# Enjoy.